### ISSUE TITLE
Failed to create plugin MKLDNNPlugin.dll for device CPU

### ISSUE THREAD

**Issue by nezarfadle** [intuiface/FaceDetectionIA#1]
I am having this issue when I try to launch the ```run_server_cpu.bat``` batch file.

![alt text](https://i.ibb.co/6vJmQHc/error.png)

```
C:\OpenVINOFaceDetectionServer>run_server_cpu.bat

C:\OpenVINOFaceDetectionServer>OpenVINOFaceDetectionServer.exe -i cam -m .\models\face-detection-adas-0001.xml -m_ag .\models\age-gender-recognition-retail-0013.xml -m_em .\models\emotions-recognition-retail-0003.xml -m_hp .\models\head-pose-estimation-adas-0001.xml -d CPU
InferenceEngine: 00007FFB1A87B740
[ INFO ] Parsing input parameters
[ INFO ] Reading input
[ INFO ] Loading device CPU
[ WARN:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2019R4\build\windows\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback
[ ERROR ] Failed to create plugin C:\OpenVINOFaceDetectionServer\MKLDNNPlugin.dll for device CPU
Please, check your environment
Cannot load library 'C:\OpenVINOFaceDetectionServer\MKLDNNPlugin.dll': 1114 from cwd: C:\OpenVINOFaceDetectionServer
```
I am using :

```
Windows 10
Built-In Webcam ( HP HD Webcam [Fixed] )
```

**Comment by nezarfadle** [comment]
Is there any update on this ?

@nicolas-daures

**Comment by SebMeunier** [comment]
Hi @nezarfadle . 

Can you precise on which PC / CPU are you trying to run this FaceDetectionServer please?

**Comment by nezarfadle** [comment]
Hey @SebMeunier 

Here is the CPU specs:

![image](https://user-images.githubusercontent.com/6154103/83955815-af1b2880-a889-11ea-8d80-d4b6996a9c43.png)

**Comment by SebMeunier** [comment]
Hi @nezarfadle 

[Intel's requirements ](https://software.intel.com/content/www/us/en/develop/tools/openvino-toolkit/system-requirements.html) for OpenVINO state "_6th to 10th generation Intel® Core™ and Intel® Xeon® processors_"

Regarding our FaceDetection server, we [recommend here ](https://support.intuiface.com/hc/en-us/articles/360013098099-Interface-Asset-Face-Detection-with-OpenVINO-#3-hardware-prerequisites) _at least an 8th gen i5_

Your CPU is a 3rd gen, so it's below both requirement & recommendation.

**Comment by nezarfadle** [comment]
Hey @SebMeunier ,

Thank you very much for the clarification, it makes sense now.

I think this issue can be closed now.
